site_name: pylib documentation


repo_url: 'https://github.com/ss249tp/pylib'
repo_name: 'ss249tp/pylib'


nav:
- README.md
- API: api.md
- Releases: releases.md


theme:

  name: material

  language: en

  icon:
    logo: simple/python

  features:
  - navigation.prune
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - toc.follow
  - toc.integrate
  - search.highlight
  - search.suggest

  palette:

  # State: Light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: 'Light -> Dark'
    primary: 'black'
    accent: indigo

  # State: Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: 'Dark -> Light'
    primary: black


extra:

  social:
  - icon: fontawesome/brands/github
    link: 'https://github.com/ss249tp/pylib'
  - icon: simple/pypi
    link: 'https://test.pypi.org/project/ss249tp-pylib/'


plugins:
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          docstring_section_style: list
          line_length: 60
          members_order: source
          separate_signature: true
          show_root_toc_entry: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
- offline
- search


markdown_extensions:

# Python Markdown
- admonition
- attr_list
- toc:
    permalink: true
    toc_depth: 3

# Python Markdown Extensions
- pymdownx.arithmatex:
    generic: true
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences


extra_javascript:
- javascripts/katex.js
- https://unpkg.com/katex@0/dist/katex.min.js
- https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
- https://unpkg.com/katex@0/dist/katex.min.css
